### ISSUE TITLE
AttributeError: 'ExpressionNode' object has no attribute 'name'

### ISSUE THREAD

**Issue by oppianmatt** [django-money/django-money#119]
upgrading from 0.4.1 to 0.5.0 and I get this error. Django 1.6.11

```
Traceback (most recent call last):
  File "/Users/matt/Source/Pitchup.com/pitchup/campsite/tests/test_search.py", line 215, in setUp
    self.check_dirty()
  File "/Users/matt/Source/Pitchup.com/pitchup/campsite/tests/test_search.py", line 253, in check_dirty
    check_dirty_task()
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/Users/matt/Source/Pitchup.com/pitchup/availability_management/tasks/__init__.py", line 28, in check_dirty_task
    check_dirty_pitch_type_task.delay(pitchtype_id)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/celery/app/task.py", line 551, in apply_async
    link=link, link_error=link_error, **options)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/celery/app/task.py", line 743, in apply
    request=request, propagate=throw)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/celery/app/trace.py", line 355, in eager_trace_task
    uuid, args, kwargs, request)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/matt/Source/Pitchup.com/pitchup/availability_management/tasks/__init__.py", line 69, in check_dirty_pitch_type_task
    arrival_day_dates.update([a.date for a in allocation_day.arrival_days])
  File "/Users/matt/Source/Pitchup.com/pitchup/booking/models/__init__.py", line 2410, in arrival_days
    date__lte=self.date)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 163, in filter
    return self.get_queryset().filter(*args, **kwargs)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/djmoney/models/managers.py", line 57, in decorator
    kwargs = _expand_money_params(kwargs)
  File "/Users/matt/Source/Pitchup.com/venv/lib/python2.7/site-packages/djmoney/models/managers.py", line 38, in _expand_money_params
    to_append['_'.join([clean_name, 'currency'])] = F('_'.join([value.name, 'currency']))
AttributeError: 'ExpressionNode' object has no attribute 'name'
```

**Comment by benjaoming** [comment]
Thanks for the report, sorry there were no reactions. Closing this, feel free to open if you can recreate it on  0.7.2  or later!
