### ISSUE TITLE
django 1.8 and migrations?

### ISSUE THREAD

**Issue by YAmikep** [django-money/django-money#128]
Does anybody have issues with migrations on django 1.8?
It does not seem to work.

After adding the following to a Model:
```
amount = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')
```

I get this error when running the django `makemigrations` command:
```
ValueError: Cannot serialize: 0 USD
There are some values Django cannot serialize into migration files.
For more, see https://docs.djangoproject.com/en/1.8/topics/migrations/#migration-serializing
```

**Comment by thnee** [comment]
+1 Upgraded from 0.7.0 to 0.7.1 and got this
```
Traceback (most recent call last):
  File "gotham/manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/core/management/commands/makemigrations.py", line 143, in handle
    self.write_migration_files(changes)
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/core/management/commands/makemigrations.py", line 171, in write_migration_files
    migration_string = writer.as_string()
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/db/migrations/writer.py", line 166, in as_string
    operation_string, operation_imports = OperationWriter(operation).serialize()
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/db/migrations/writer.py", line 124, in serialize
    _write(arg_name, arg_value)
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/db/migrations/writer.py", line 75, in _write
    arg_string, arg_imports = MigrationWriter.serialize(item)
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/db/migrations/writer.py", line 303, in serialize
    item_string, item_imports = cls.serialize(item)
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/db/migrations/writer.py", line 377, in serialize
    return cls.serialize_deconstructed(path, args, kwargs)
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/db/migrations/writer.py", line 268, in serialize_deconstructed
    arg_string, arg_imports = cls.serialize(arg)
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/db/migrations/writer.py", line 465, in serialize
    "topics/migrations/#migration-serializing" % (value, get_docs_version())
ValueError: Cannot serialize: 0 XYZ
There are some values Django cannot serialize into migration files.
For more, see https://docs.djangoproject.com/en/1.8/topics/migrations/#migration-serializing
Traceback (most recent call last):
  File "/home/vagrant/venvs/gotham/lib/python3.4/site-packages/django/db/migrations/loader.py", line 159, in check_key
    return list(self.graph.root_nodes(key[0]))[0]
IndexError: list index out of range
```

**Comment by benjaoming** [comment]
> +1 Upgraded from 0.7.0 to 0.7.1 and got this

I don't remember seeing any changes with regards to django.db.migrations in 0.7.0 - 0.7.1 -- does the error happen on 0.7.0 or not?

**Comment by thnee** [comment]
Actually, it appears that it doesn't matter if it it is version 0.7.0 or 0.7.1 of django-money. Rather, the problem occurrs when py-moneyed is upgraded from 0.5.0 to 0.6.0. Sorry for the confusion.

**Comment by benjaoming** [comment]
@thnee you mean that things are working with py-moneyed 0.5.0 and not 0.6.0?

**Comment by thnee** [comment]
@benjaoming correct.

**Comment by tiberius** [comment]
i can confirm: 
```
Django==1.8.4
django-money==0.7.1
py-moneyed==0.5.0
```
works well

```
Django==1.8.4
django-money==0.7.1
py-moneyed==0.6.0
```
fails with the above ValueError

**Comment by sjdines** [comment]
I am having similar issues with the `ValueError` appearing when using `py-moneyed==0.5.0` or `py-moneyed==0.6.0` with `Django==1.8.4` and `django-money==0.7.1` or `django-money==0.7.0`.


End of error output:

    ValueError: Cannot serialize: 0 AUD
    There are some values Django cannot serialize into migration files.
    For more, see https://docs.djangoproject.com/en/1.8/topics/migrations/#migration-serializing

**Comment by benjaoming** [comment]
#130 has been merged -- any chance anyone can make a second verification of the patch?

**Comment by tiberius** [comment]
```
Django==1.8.4
-e git://github.com/django-money/django-money@f0a8b4488fb484adb68abf4c7b7b9070275845da#egg=django_money-origin/HEAD
py-moneyed==0.6.0
```
does no longer crash with the above error

**Comment by benjaoming** [comment]
Thanks for pitching in, @tiberius , closing this then

**Comment by synotna** [comment]
Remember to push out a new pypi version

p.s. github master setup.py somehow has the version 0.7.0

**Comment by benjaoming** [comment]
Thanks @synotna - done and added a tag for 01b89fc which AFAIK was release 0.7.1.
