### ISSUE TITLE
NotImplementedError: Django 1.8+ support is not implemented.

### ISSUE THREAD

**Issue by oppianmatt** [django-money/django-money#153]
Docs state django 1.8 is supported. The code says otherwise.

Doing a simple F query and djmoney throws the exception.

code is at https://github.com/django-money/django-money/blob/master/djmoney/models/managers.py#L43

Clearly checks for django version and says django 1.8 not supported.

```
def _get_field(model, name):
    if django.VERSION[0] >= 1 and django.VERSION[1] >= 8:
        # Django 1.8+ - can use something like 
        # expression.output_field.get_internal_field() == 'Money..'
        raise NotImplementedError("Django 1.8+ support is not implemented.")
```

**Comment by benjaoming** [comment]
Are you saying that `# expression.output_field.get_internal_field() == 'Money..'` doesnt work?

**Comment by benjaoming** [comment]
Could you maybe supply a traceback of a failing `F()` expression?

**Comment by oppianmatt** [comment]
```
/Users/matt/Source/xx/xx/xx/models/__init__.pyc in arrival_days(self)
   3015                                          # charge_type__is_active=True,
   3016                                          date__gt=self.date - F("pricing_period"),
-> 3017                                          date__lte=self.date)
   3018
   3019     def set_pitches_to_sell(self, value):

/Users/matt/.virtualenvs/xx/lib/python2.7/site-packages/django/db/models/manager.pyc in manager_method(self, *args, **kwargs)
    125         def create_method(name, method):
    126             def manager_method(self, *args, **kwargs):
--> 127                 return getattr(self.get_queryset(), name)(*args, **kwargs)
    128             manager_method.__name__ = method.__name__
    129             manager_method.__doc__ = method.__doc__

/Users/matt/.virtualenvs/xx/lib/python2.7/site-packages/djmoney/models/managers.pyc in wrapper(*args, **kwargs)
    154         args = _expand_money_args(model, args)
    155         kwargs = kwargs.copy()
--> 156         kwargs = _expand_money_kwargs(model, kwargs)
    157         return func(*args, **kwargs)
    158

/Users/matt/.virtualenvs/xx/lib/python2.7/site-packages/djmoney/models/managers.pyc in _expand_money_kwargs(model, kwargs)
    129                 value.currency)
    130         if isinstance(value, BaseExpression):
--> 131             field = _get_field(model, name)
    132             if isinstance(field, MoneyField):
    133                 clean_name = _get_clean_name(name)

/Users/matt/.virtualenvs/xx/lib/python2.7/site-packages/djmoney/models/managers.pyc in _get_field(model, name)
     44         # Django 1.8+ - can use something like
     45         # expression.output_field.get_internal_field() == 'Money..'
---> 46         raise NotImplementedError("Django 1.8+ support is not implemented.")
     47
     48     from django.db.models.fields import FieldDoesNotExist

NotImplementedError: Django 1.8+ support is not implemented.
```

Where does one use the proposed `expression.output_field.get_internal_field() == 'Money..'` ? As you can see from the traceback there is no chance as it goes straight into django code.

Normal traceback:

```
Traceback (most recent call last):
  File "/Users/matt/.virtualenvs/pitchup/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-68ea4ca4a9a8>", line 1, in <module>
    allocation_day.arrival_days()
  File "/Users/matt/Source/xx/xx/booking/models/__init__.py", line 3017, in arrival_days
    date__lte=self.date)
  File "/Users/matt/.virtualenvs/xx/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/matt/.virtualenvs/xx/lib/python2.7/site-packages/djmoney/models/managers.py", line 156, in wrapper
    kwargs = _expand_money_kwargs(model, kwargs)
  File "/Users/matt/.virtualenvs/xx/lib/python2.7/site-packages/djmoney/models/managers.py", line 131, in _expand_money_kwargs
    field = _get_field(model, name)
  File "/Users/matt/.virtualenvs/pitchup/lib/python2.7/site-packages/djmoney/models/managers.py", line 46, in _get_field
    raise NotImplementedError("Django 1.8+ support is not implemented.")
NotImplementedError: Django 1.8+ support is not implemented.
```

The query is just:

```
ArrivalDay.objects.filter(charge_type__pitchtype=self.pitchtype,
                                         date__gt=self.date - F("pricing_period"),
                                         date__lte=self.date)
```

It retrieves day objects that match the date and cover the pricing period.

When it gets into `_expand_money_kwargs` and iterates through the kwargs, the kwarg value that contains the F expression tests true for being a `BaseExpression` which then runs the code that says django 1.8 isn't supported.

**Comment by benjaoming** [comment]
> As you can see from the traceback there is no chance as it goes straight into django code.

No quite:

```
  File "/Users/matt/.virtualenvs/xx/lib/python2.7/site-packages/djmoney/models/managers.py", line 156, in wrapper
    kwargs = _expand_money_kwargs(model, kwargs)
  File "/Users/matt/.virtualenvs/xx/lib/python2.7/site-packages/djmoney/models/managers.py", line 131, in _expand_money_kwargs
    field = _get_field(model, name)
  File "/Users/matt/.virtualenvs/pitchup/lib/python2.7/site-packages/djmoney/models/managers.py", line 46, in _get_field
    raise NotImplementedError("Django 1.8+ support is not implemented.")
NotImplementedError: Django 1.8+ support is not implemented.
```

...this is happening in djmoney, so I would think the fix is in `djmoney/models/managers.py, line 131, in _expand_money_kwargs`

**Comment by oppianmatt** [comment]
Yes that's what I meant, that there is no chance in user code to do the _get_field proposal as it goes straight into django then djmoney.

**Comment by oppianmatt** [comment]
Note this issue happens even when the F expression is NOT using the money field at all.

**Comment by benjaoming** [comment]
In that case djmoney fields basically break Django 1.8+ projects, that sounds pretty bad :/

**Comment by toudi** [comment]
please check my PR to #155. There was a hard-coded exception, even though the tests pass *and* there already is a support for Django 1.9

```
if django.VERSION[0] >= 1 and django.VERSION[1] >= 8:
        # Django 1.8+ - can use something like 
        # expression.output_field.get_internal_field() == 'Money..'
        raise NotImplementedError("Django 1.8+ support is not implemented.")
```

**Comment by benjaoming** [comment]
@toudi thanks for the work getting django-money to 1.8 and 1.9 support

@oppianmatt could you check the current master?
