### ISSUE TITLE
django.core.exceptions.FieldError with __date lookup and money_manager()

### ISSUE THREAD

**Issue by goetzb** [django-money/django-money#241]
I am using Django 1.9 and django-money 0.9.1. While refining my data structure and testing some models, I noticed that the `__date` lookup that was added in Django 1.9 (https://docs.djangoproject.com/en/1.9/ref/models/querysets/#date) does not seem to work properly with `money_manager()`.

In all models which use a `MoneyField()`, `__date` lookups result in an exception like this:
`django.core.exceptions.FieldError: Cannot resolve keyword 'date' into field. Join on 'my_datetime_field' not permitted.`

When I attach an additional model manager to the model without wrapping it in `money_manager()`, the `__date` lookup works fine on that new manager.

Looking through the traceback in more detail revealed that `djmoney.models.managers.money_manager()` seems to cause the problem:
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/[...]/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/[...]/python3.4/site-packages/djmoney/models/managers.py", line 164, in wrapper
    args, kwargs = _expand_money_kwargs(model, args, kwargs, exclusions)
  File "/[...]/python3.4/site-packages/djmoney/models/managers.py", line 136, in _expand_money_kwargs
    elif isinstance(_get_field(model, name), MoneyField):
  File "/[...]/python3.4/site-packages/djmoney/models/managers.py", line 63, in _get_field
    field = qs.setup_joins(parts, opts, alias)[0]
  File "/[...]/python3.4/site-packages/django/db/models/sql/query.py", line 1405, in setup_joins
    names, opts, allow_many, fail_on_missing=True)
  File "/[...]/python3.4/site-packages/django/db/models/sql/query.py", line 1373, in names_to_path
    " not permitted." % (names[pos + 1], name))
django.core.exceptions.FieldError: Cannot resolve keyword 'date' into field. Join on 'my_datetime_field' not permitted.
```

Perhaps you can work out what exactly is going wrong. If you need any additional information, please get in touch. Thanks!

**Comment by Stranger6667** [comment]
Thank you for the report! The fix is merged to master :)
