### ISSUE TITLE
using factory_boy with MoneyField gives Attribute Error

### ISSUE THREAD

**Issue by mithrilstar** [django-money/django-money#297]
I have a `Transaction` model which uses a `MoneyField`. While writing tests, I realised that creating a test transaction object using the std django orm way via Transaction.objects.create() etc works ok but using factory_boy to create the same doesn't. Please help me out if I'm going about this wrong.

This is my model:
```
class Transaction(Timestampable, models.Model):
    amount = MoneyField(decimal_places=2, max_digits=10, default_currency='INR')
    # todo - default currency should be picked from profile/person
    # note2self - as of now a tx can have a single associated category but multiple tags are possible
    category = models.ForeignKey(Category, related_name="category_transactions", blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name="tag_transactions")  # also optional
    created_by = models.ForeignKey(Person, related_name="transactions")
    transaction_date = models.DateField()
    transaction_time = models.TimeField(blank=True, null=True)
```

This is the simplified factory and other code
```
class MoneyProvider(BaseProvider):
     def money(self):
        return Money(563, INR)

fake = Faker()
fake.add_provider(MoneyProvider)

class TransactionFactory(factory.DjangoModelFactory):
    """
        Factory used to instantiate class Transaction
        """

    class Meta:
        model = Transaction

    created_by = factory.SubFactory(PersonFactory)
    amount = fake.money()
    transaction_date = fake.date_time_between(start_date='-3d').date()
    transaction_time = None

    tags = None
    category = None
```
This is my test file

```
class TestTransactionModel(TestCase):
    def setUp(self):
        self.transaction = TransactionFactory.create(amount=Money(563, INR))
        # self.transaction = Transaction.objects.create(
        #     amount=Money(563, INR),
        #     created_by=PersonFactory.create(),
        #     transaction_date=timezone.now().date()
        # )

    def tearDown(self):
        self.transaction.delete()

    def test_something(self):
        pass
```
On running this i get 

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E.
======================================================================
ERROR: test_something (doubloon.transactions.tests.test_models.TestTransactionModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/myrtle/03_django_projects/doubloon/doubloon/transactions/tests/test_models.py", line 13, in setUp
    self.transaction = TransactionFactory.create(amount=Money(563, INR))
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/factory/base.py", line 623, in create
    return cls._generate(True, attrs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/factory/base.py", line 548, in _generate
    obj = cls._prepare(create, **attrs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/factory/base.py", line 523, in _prepare
    return cls._create(model_class, *args, **kwargs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/factory/django.py", line 181, in _create
    return manager.create(*args, **kwargs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/db/models/query.py", line 392, in create
    obj = self.model(**kwargs)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/db/models/base.py", line 559, in __init__
    property_names = opts._property_names
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/db/models/options.py", line 890, in _property_names
    dir(self.model) if isinstance(getattr(self.model, attr), property)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/django/db/models/options.py", line 890, in <setcomp>
    dir(self.model) if isinstance(getattr(self.model, attr), property)
  File "/home/myrtle/03_django_projects/environments/doubloon/lib/python3.5/site-packages/djmoney/models/fields.py", line 225, in __get__
    raise AttributeError('Can only be accessed via an instance.')
AttributeError: Can only be accessed via an instance.
```
What am i doing wrong?

**Comment by Stranger6667** [comment]
Hello, please tell me what Django / django-money version are you using?
I'll take a look at the issue on the weekend.

**Comment by Stranger6667** [comment]
So, there is a bug in django-money and it was in the codebase since 15.05.2011. I think, it will be possible to make a bugfix release 0.11.1 without latest changes (dropping support for Python 2.6 and Django < 1.8). 

I'll do a new branch from 0.11 tag, do a backport from the master branch and add 0.11.1 tag. @benjaoming what do you think about a bugfix release? 

Here is a PR - #298

**Comment by mithrilstar** [comment]
Hi my django is version 1.11.1 and django-money at 0.10.2

Having a bugfix release 0.11.1 would fix it for me perfectly :) I'm still in the early stages of my project so updating requirements is not an issue at all. Thanks for taking such an awesomely quick look at the issue.

**Comment by Stranger6667** [comment]
Thank you for the bag report! You're very welcome :) 

@benjaoming, new tag 0.11.1 is created and ready to be released on PyPI :) master also has this fix merged
