### ISSUE TITLE
Amount with currency not serializing at all.

### ISSUE THREAD

**Issue by arslanhashmi** [django-money/django-money#463]
Model: 
```python
class EmployeeSalary(models.Model):
    employee = models.OneToOneField(Employee, on_delete=models.DO_NOTHING, null=True, blank=True)
    salary = MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, default=None, null=True)
```

Serializer:
```python
class EmployeeSalarySerializer(serializers.ModelSerializer):

    class Meta:
        fields = ('employee', 'salary')
        model = EmployeeSalary
```

During serializing following error comes.
```python
EmployeeSalarySerializer(EmployeeSalary.objects.get(pk=1)).data

Traceback (most recent call last):
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/arslan/PycharmProjects/montel/heman/employees/views.py", line 51, in stats
    payload = dict(potential=potential, utilization=utilization, utilization_history=history, salary=salary.data)
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/rest_framework/serializers.py", line 765, in data
    ret = super(ListSerializer, self).data
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/rest_framework/serializers.py", line 683, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/rest_framework/serializers.py", line 683, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/rest_framework/serializers.py", line 527, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/arslan/.virtualenvs/heman/lib/python3.6/site-packages/rest_framework/fields.py", line 1107, in to_representation
    value = decimal.Decimal(six.text_type(value).strip())
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

Debugging shown that like the `to_representation` function from `MoneyField` is not executing, in fact, field is looked up as `DecimalField` rather than `MoneyField` by rest-framework.

**Comment by arslanhashmi** [comment]
@Stranger6667 may you pease tell what could be the problem?

**Comment by arslanhashmi** [comment]
No worries, there was a silly mistake from my side, I forgot to add `djmoney` in `INSTALLED_APPS`.
