### ISSUE TITLE
Support for python 3.6

### ISSUE THREAD

**Issue by laidbackpeter** [django-money/django-money#469]
@Stranger6667 @benjaoming 
I am getting this traceback while porting from python 2.7 to python 3.6.6

I am using the below on a virtual env:
django == 1.11.17
django-money == 0.14.4
python == 3.6.6

```
Traceback (most recent call last):
  File "manage.py", line 33, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 164, in handle
    pre_migrate_apps = pre_migrate_state.apps
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/db/migrations/state.py", line 218, in apps
    return StateApps(self.real_apps, self.models)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/db/migrations/state.py", line 288, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/db/migrations/state.py", line 323, in render_multiple
    model.render(self)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/db/migrations/state.py", line 626, in render
    body,
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/db/models/base.py", line 162, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/djmoney/models/fields.py", line 248, in contribute_to_class
    self.add_currency_field(cls, name)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/djmoney/models/fields.py", line 265, in add_currency_field
    cls.add_to_class(currency_field_name, currency_field)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/djmoney/models/fields.py", line 166, in contribute_to_class
    super(CurrencyField, self).contribute_to_class(cls, name)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 704, in contribute_to_class
    self.set_attributes_from_name(name)
  File "/Users/peter.muchina/PycharmProjects/pulaphones/django/website/.ve/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 687, in set_attributes_from_name
    self.verbose_name = self.name.replace('_', ' ')
TypeError: a bytes-like object is required, not 'str'
```

kindly assist.

**Comment by washeck** [comment]
@laidbackpeter django-money is supported (and tested) on Python 3.6 so I suspect the problem is somewhere else. Can you provide your models.py code?

May I also aks you to use the Preview function of GitHub editor and format the code - the traceback in your issue desciption is difficult to read. Thank you.

**Comment by laidbackpeter** [comment]
@washeck 
`
from djmoney.models.fields import CurrencyField

class IncentivePrototype(AbstractBase):
    """Necessary fields for incentives."""

    class Meta(object):
        abstract = True
        unique_together = ('name', 'season')

    name = models.CharField(max_length=100)
    currency = CurrencyField()
    country = CountryField()`

Only model where we are using CurrencyField()

**Comment by washeck** [comment]
@laidbackpeter I'm afraid this has nothing to do with django-money but rather with your 2.7 to 3.6 migration which is difficult to debug without having your full source code. It looks like the name of your field is bytes object instead of string.

I'd suggest to add debugger or print() to `set_attributes_from_name` and debug what's going on. Or to provide a minimal project which reproduces the error you are getting.

**Comment by washeck** [comment]
@laidbackpeter You might also check your migrations generated on 2.x Python if they contain byte literals. See https://code.djangoproject.com/ticket/23226

**Comment by laidbackpeter** [comment]
@washeck you were spot on. The issue was with the migrations. Much appreciation, you have unblocked me big time. Again, thank you.
