### ISSUE TITLE
Why isnot it have right behaviour m + 0 = m?

### ISSUE THREAD

**Issue by satels** [django-money/django-money#531]
```python
root@cefe187eb016:/var/www/cabinet# ./manage.py shell
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from djmoney.money import Money
>>> m = Money(1, 'RUB')
>>> m + 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/djmoney/money.py", line 33, in __add__
    other = maybe_convert(other, self.currency)
  File "/usr/local/lib/python3.6/dist-packages/djmoney/money.py", line 103, in maybe_convert
    return convert_money(value, currency)
  File "/usr/local/lib/python3.6/dist-packages/djmoney/contrib/exchange/models.py", line 109, in convert_money
    amount = value.amount * get_rate(value.currency, currency)
AttributeError: 'int' object has no attribute 'amount'
>>> 0 + m
<Money: 1 RUB>
```

**Comment by lieryan** [comment]
From my understanding the special handling of allowing `0 + Money()` was just to make `sum([Money(), Money()])` works. This behaviour comes from the underlying python-moneyed library. 

There are also other various other zero related and reverse operator bugs in moneyed like `0 - Money()`. 

Basically, addition and subtraction of Money with non-Money numbers aren't really supported.

**Comment by satels** [comment]
Operations moneys with 0 (zero integer) should be supported with django-money and moneyed (this really make sense), because you were worrying about initialization of currency, even if (for example) a user haven't increased himself account balance (especially if you are proccessing our users with different countries as one process)
