### ISSUE TITLE
AttributeError: 'function' object has no attribute 'amount'

### ISSUE THREAD

**Issue by juandisay** [django-money/django-money#602]
Hello, there are an AttributeError: 'function' object has no attribute 'amount'.
Has anyone here ever experienced something like this?

Stack:
Python 3.6.9
Django 3.1.3

**My log**
```
Traceback (most recent call last):
  File "apps/manage.py", line 22, in <module>
    main()
  File "apps/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 182, in handle
    self.write_migration_files(changes)
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 219, in write_migration_files
    migration_string = writer.as_string()
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/db/migrations/writer.py", line 141, in as_string
    operation_string, operation_imports = OperationWriter(operation).serialize()
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/db/migrations/writer.py", line 99, in serialize
    _write(arg_name, arg_value)
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/db/migrations/writer.py", line 63, in _write
    arg_string, arg_imports = MigrationWriter.serialize(_arg_value)
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/db/migrations/writer.py", line 271, in serialize
    return serializer_factory(value).serialize()
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/django/db/migrations/serializer.py", line 198, in serialize
    attr_name, path, args, kwargs = self.value.deconstruct()
  File "/home/juandisay/.pyenv/versions/+3KLESAVING/lib/python3.6/site-packages/djmoney/models/fields.py", line 300, in deconstruct
    kwargs["default"] = self.default.amount
AttributeError: 'function' object has no attribute 'amount'

```

Thanks

**Comment by Stranger6667** [comment]
Hi! Thank you for reporting!

It seems like we missed supporting callable `default` :) Will work on that

**Comment by juandisay** [comment]
@Stranger6667  Thanks so much to answerr..
I try fixed, I append code like this, and it works.

```
def deconstruct(self):
        name, path, args, kwargs = super().deconstruct()

        if self.default is None:
            del kwargs["default"]
        if self.default_currency is None:
            kwargs["default_currency"] = self.default_currency
        if self.default_currency is not None and self.default_currency != DEFAULT_CURRENCY:
            kwargs["default_currency"] = str(self.default_currency)
        if self.currency_choices != CURRENCY_CHOICES:
            kwargs["currency_choices"] = self.currency_choices
        if self.currency_field_name:
            kwargs["currency_field_name"] = self.currency_field_name
        return name, path, args, kwargs
```

**Comment by Stranger6667** [comment]
Thank you for providing this snippet! I need to check it deeper :)

It is strange to have a callable in migration since having `default` as a callable will raise a `ValueError`. Could you, please, share your model setup?

Also, what command did you run to get that traceback?
