### ISSUE TITLE
Updating MoneyField through update_or_create causes error

### ISSUE THREAD

**Issue by PetrDlouhy** [django-money/django-money#695]
I have following model:

```python
class RunningTotal(models.Model):
    account = models.ForeignKey(
        "hordak.Account", on_delete=models.CASCADE, related_name="running_totals"
    )
    currency = models.CharField(
        max_length=15,
    )
    balance = MoneyField(
        max_digits=MAX_DIGITS,
        decimal_places=DECIMAL_PLACES,
        default_currency=defaults.DEFAULT_CURRENCY,
        null=True,
        blank=True,
    )
```

When I try to update the balance field with:

```python
def _update_running_totals(instance, amount_change):
    RunningTotal.objects.update_or_create(
        account=instance.account,
        currency=instance.amount.currency,
        defaults={'balance': F('balance') + amount_change}
    )
```

I got following error:
```python
  File "/home/petr/soubory/programovani/blenderkit/django-hordak/hordak/receivers.py", line 9, in _update_running_totals
    RunningTotal.objects.update_or_create(
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 962, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 936, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 669, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/django/db/models/base.py", line 544, in __init__
    _setattr(self, field.attname, val)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/djmoney/models/fields.py", line 121, in __set__
    validate_money_expression(obj, value)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/djmoney/models/fields.py", line 51, in validate_money_expression
    lhs = get_value(obj, expr.lhs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/djmoney/models/fields.py", line 34, in get_value
    expr = getattr(obj, expr.name)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.11/lib/python3.11/site-packages/djmoney/models/fields.py", line 102, in __get__
    if isinstance(data[self.field.name], BaseExpression):
                  ~~~~^^^^^^^^^^^^^^^^^
KeyError: 'balance'
```

**Comment by PetrDlouhy** [comment]
I found, that this might be irrelevant issue, because if I tried to overpass the validate_money_expression() I have got following error:
```
ValueError: Failed to insert expression "Col(hordak_runningtotal, hordak.RunningTotal.balance) + Value(Decimal('100'))" on hordak.RunningTotal.balance. F() expressions can only be used to update, not to insert.
```

But on the other hand, the original error is very cryptical and hides the Django's obvious error message.

**Comment by karolyi** [comment]
Same here.

Easily reproducible by the following code (assuming you have a model with a `MoneyField` field on it):
```python
In [41]: Payment.objects.only('pk').first().price
SELECT `project_app_payment`.`id`
  FROM `project_app_payment`
 ORDER BY `project_app_payment`.`arrived_at` DESC
 LIMIT 1

Execution time: 0.000249s [Database: default]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[41], line 1
----> 1 Payment.objects.only('pk').first().price

File ~/Work/project/venv/lib/python3.10/site-packages/djmoney/models/fields.py:102, in MoneyFieldProxy.__get__(sel
f, obj, type)
    100     return self
    101 data = obj.__dict__
--> 102 if isinstance(data[self.field.name], BaseExpression):
    103     return data[self.field.name]
    104 if not isinstance(data[self.field.name], Money):

KeyError: 'price'

```
